# Generated by Django 5.2.4 on 2025-08-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='anomalies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='audit_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
