# Generated by Django 5.2.4 on 2025-08-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbot_anomalies_chatbot_audit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('spreadsheet', 'Tableur'), ('presentation', 'Présentation'), ('other', 'Autre')], default='other', max_length=20)),
                ('file_size', models.IntegerField(help_text='Taille en bytes')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chatbot.utilisateur')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
